Gunluk<-function(a,unique_isim,mean_isim,any_isim,agg_isim){
  in1<-which(names(a) %in% unique_isim)
  in2<-which(names(a) %in% mean_isim)
  in3<-which(names(a) %in% any_isim)
  #in4<-which(names(a) %in% identical)
  a$Year<-as.character(a$Year)
  a$Month<-as.character(a$Month)
  print(dim(a))
  source("Agg_Columns.R")
  mean_x<-Agg_Columns(a,mean_isim,agg_isim,mean)
  print(mean_x)
  unique_x<-Agg_Columns(a,unique_isim,agg_isim,func<-function(x){unique(x)})
  any_x<-Agg_Columns(a,any_isim,agg_isim,func<-function(x){if(sum(x==1)>0){1}else{0}})
  #identical_x<-Agg_Columns(a,identical,agg_isim,func<-function(x){(x)})
  x<-merge(any_x,unique_x, by=agg_isim)
  x<-merge(x,mean_x,by=agg_isim)
  #x<-merge(x,identical_x, by=agg_isim)
  x$Year<-as.character(x$Year)
  x$Month<-as.character(x$Month)
  print(names(x))
  #x$MonthDT<-as.character(x$MonthDT)
  return(x)
}